var teens7D773=[
	{"word":"experiment","class":"n","trans":"实验","other":["experimental &emsp;&emsp; adj.实验性的"],"phrase":["do an experiment &emsp;&emsp; 做实验"],"example":["I'm doing an <b>experiment</b> in the Shenzhen <b>Experimental</b> School &emsp;&emsp; 我正在深圳实验学校做实验","That <b>experiment</b> is so danger! &emsp;&emsp; 那个实验太危险了！"]},
	{"word":"order","class":"n","trans":"秩序；命令<br>v. 命令；订购","other":["orders &emsp;&emsp; n.订单"],"phrase":["keep ... in order &emsp;&emsp; 使 ... 保持秩序 "," put things in order &emsp;&emsp; 把东西整理整齐 "," do sth. in order &emsp;&emsp; 按顺序做 ..."],"example":["She always <b>keeps</b> her room <b>in good order</b>. &emsp;&emsp; 她的房间总是整整齐齐的 "," Can you <b>put</b> your toys <b>in order</b> from biggest to smallest ? &emsp;&emsp; 你能把你的玩具从小到大排好吗？"]},
	{"word":"neighbor","class":"n","trans":"邻居，邻国<br>adj. 邻近的，邻接的<br>vi. 友好; 毗邻而居<br>vt. 邻接","other":["neighboring &emsp;&emsp; adj.邻近的 ","<br>"," 复数: neighbors "," 三单: neighbors "," 过去式: neighbored "," 过去分词: neighbored "," 现在分词: neighboring"],"phrase":["None"],"example":["Who is my <b>neighbor</b> ? &emsp;&emsp; 谁是我的邻居？ "," He is having his holiday in a <b>neighboring</b> city. &emsp;&emsp; 他正在临近的城市度假"]},
	{"word":"die","class":"v","trans":"死<br>n. 模具","other":["dead &emsp;&emsp; n.死(者)；adj.死的 "," <br> "," 三单: dies "," 过去式: died "," 过去分词: died "," 现在分词: dying"],"phrase":["None"],"example":["He is going to <b>die</b> ! &emsp;&emsp; 他快要死了！"]},
	{"word":"though","class":"adv","trans":"不过，但是<br>conj. 虽然","other":[""],"phrase":[""],"example":["I like it <b>though</b> it is sour. &emsp;&emsp; 我喜欢它虽然他是酸的"]},
	{"word":"character","class":"n","trans":"性格；字母(文字)","other":["复数: characters"],"phrase":[""],"example":["The Chinese <b>characters</b> is amazing ! &emsp;&emsp; 中国的汉字真神奇！"]},
	{"word":"brave","class":"adj","trans":"勇敢的，极好的<br>v. 勇敢面对<br>n. 勇士","other":["bravely &emsp;&emsp; adv.勇敢地 "," bravery &emsp;&emsp; n.勇气 "," <br> "," 复数: braves "," 三单: braves "," 过去式: braved "," 过去分词: braved "," 现在分词: braving "," 比较级: braver "," 最高级: bravest"],"phrase":["do sth. bravely &emsp;&emsp; 勇敢地做某事 "," be brave enough to do sth. &emsp;&emsp; 足够勇敢去做某事"],"example":["Fight <b>bravely</b> against the enemy ! &emsp;&emsp; 勇敢地与敌人作战！ "," He is <b>brave enough</b> to go on an adventure with me. &emsp;&emsp; 他已经足够勇敢,可以去跟我冒险了。"]},
	{"word":"calm","class":"adj","trans":"镇静的; 稳定的<br>v. 使平静; 止痛<br>n. 平静，宁静","other":["calmness &emsp;&emsp; n.平静 "," calmly &emsp;&emsp; adv.镇定自若地 "," <br> "," 复数: calms "," 三单: calms "," 过去式: calmed "," 过去分词: calmed "," 现在分词: calming "," 比较级: calmer "," 最高级: calmest"],"phrase":["calm down &emsp;&emsp; 冷静一下"],"example":["<b>Calm down</b>, Peter ! &emsp;&emsp; Peter，请冷静一下！"]},
	{"word":"form","class":"n","trans":"形态<br>v. 形成","other":["复数: forms "," 三单: forms "," 过去式: formed "," 过去分词: formed "," 现在分词: forming"],"phrase":[""],"example":["The sun <b>formed</b> 4.6 billion years ago. &emsp;&emsp; 太阳形成于4.6亿年前"]},
	{"word":"metal","class":"n","trans":"金属","other":["复数: metals "," 三单: metals "," 过去式: metalled "," 过去分词: metalled "," 现在分词: metalling"],"phrase":[""],"example":["It is made of <b>metal</b>. &emsp;&emsp; 它是金属的。"]},
	{"word":"material","class":"n","trans":"原料<br>adj.物质上的","other":["materially &emsp;&emsp; adv.物质上 "," spiritual &emsp;&emsp; adj.精神上的"],"phrase":[""],"example":["He was well-off <b>materially</b>. &emsp;&emsp; 他在物质上很富裕"]},
	
	]
	